# Generated by Django 4.2.5 on 2023-09-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="assignments_to_uploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_photo", models.ImageField(upload_to="static/images")),
                ("a_title", models.CharField(max_length=250)),
                ("a_description", models.CharField(max_length=250)),
                ("a_link", models.URLField()),
            ],
        ),
    ]
