# Generated by Django 4.2.5 on 2023-09-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignments_to_uploads",
            name="a_link",
        ),
    ]
