# Generated by Django 4.2.5 on 2023-09-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_rename_a_photo_assignments_to_uploads_a_img1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignments_to_uploads",
            name="a_img1",
            field=models.ImageField(upload_to="service/static/images"),
        ),
        migrations.AlterField(
            model_name="assignments_to_uploads",
            name="a_img2",
            field=models.ImageField(default="", upload_to="service/static/images"),
        ),
        migrations.AlterField(
            model_name="assignments_to_uploads",
            name="a_img3",
            field=models.ImageField(default="", upload_to="service/static/images"),
        ),
        migrations.AlterField(
            model_name="assignments_to_uploads",
            name="a_img4",
            field=models.ImageField(default="", upload_to="service/static/images"),
        ),
        migrations.AlterField(
            model_name="assignments_to_uploads",
            name="a_img5",
            field=models.ImageField(default="", upload_to="service/static/images"),
        ),
    ]
